ICEMapping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('datamanager.urls')),
    path('admin/', admin.site.urls),
]

datamanager/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'datamanager'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='datamanager/login.html'), name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('<str:username>/newdata/', views.newdata, name='newdata'),
    path('datalist/', views.datalist, name='datalist'),
    path('recommandation', views.recommandation, name='recommandation'),
    path('<int:geoid>/', views.detail, name='detail'),
    path('google/', views.google, name='google'),
    path('heat/', views.heat, name='heat'),
    path('<int:geoid>/deleteComment/<str:context>', views.deleteComment, name='deleteComment'),
    path('search', views.search, name='search'),
]

datamanager/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

GENDER = (
    ('', 'Choose...'),
    ('F', 'Female'),
    ('M', 'Male'),
    ('NA', 'Prefer not to answer')
)


RACE = (
    ('', 'Choose...'),
    ('B', 'Black'),
    ('W', 'White'),
    ('A', 'Asian'),
    ('O', 'Other Race'),
    ('NA', 'Prefer not to answer')
)

Age = (
    ('', 'Choose...'),
    ('Young', 'Young'),
    ('Middle', 'Middle'),
    ('Old', 'Old'),
    ('NA', 'Prefer not to answer')
)

Dept = (
    ('', 'Choose...'),
    ('North','North'),
    ('South','South'),
    ('Main','Main' )
)

RATE = (
    ('', 'Choose...'),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
)

Area = (
    ('', 'Choose...'),
    ('south', 'South Quad'),
    ('main', 'Main Quad'),
    ('engin', 'North Quad'),
)

Preference = (
    ('', 'Choose...'),
    ('-1', 'Dislike'),
    ('-0.5', 'Not good'),
    ('0', 'No prefer'),
    ('0.5', 'Good'),
    ('1', 'Prefer'),
)

#   Forms for user to filled out. I use the 'crispy_forms' API to beautify the form.
#   You can google this API to see how it works and use their documentation as reference.
class UserInfoForm(forms.Form):
    geoid = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'GeoID'}))
    age = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Your age'}))
    race = forms.ChoiceField(choices=RACE)
    gender = forms.ChoiceField(choices=GENDER)
    dept = forms.ChoiceField(choices=Dept)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('geoid', css_class='form-group col-md-6 mb-0'),
                Column('age', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('dept', css_class='form-group col-md-4 mb-0'),
                Column('race', css_class='form-group col-md-4 mb-0'),
                Column('gender', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', 'Submit')
        )

class CommentForm(forms.Form):
    rate = forms.ChoiceField(choices=RATE)
    comment = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Leave your comment: '}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'rate',
            'comment',
            Submit('submit', 'Submit')
        )

# input_data = [Pop, White, Black, Asian, OtherRace, Male, Female, Young, Middle, Old, Sdist, Ndist, Mdist]
class recommandationForm(forms.Form):
    young = forms.ChoiceField(choices=Preference, initial= '1')
    old = forms.ChoiceField(choices=Preference,initial= '1')
    middle = forms.ChoiceField(choices=Preference, initial= '1')
    white = forms.ChoiceField(choices=Preference, initial= '1')
    black = forms.ChoiceField(choices=Preference, initial= '1')
    asian = forms.ChoiceField(choices=Preference, initial= '1')
    otherrace = forms.ChoiceField(choices=Preference, initial= '1')
    population = forms.ChoiceField(choices=Preference, initial= '1')
    male = forms.ChoiceField(choices=Preference, initial= '1')
    female = forms.ChoiceField(choices=Preference, initial= '1')
    south = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Acceptable distance away from south quad'}))
    main = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Acceptable distance away from main quad'}))
    north = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Acceptable distance away from north quad'}))


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('young', css_class='form-group col-md-4 mb-0'),
                Column('middle', css_class='form-group col-md-4 mb-0'),
                Column('old', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('black', css_class='form-group col-md-3 mb-0'),
                Column('white', css_class='form-group col-md-3 mb-0'),
                Column('asian', css_class='form-group col-md-3 mb-0'),
                Column('otherrace', css_class='form-group col-md-3 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('population', css_class='form-group col-md-4 mb-0'),
                Column('male', css_class='form-group col-md-4 mb-0'),
                Column('female', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('south', css_class='form-group col-md-4 mb-0'),
                Column('main', css_class='form-group col-md-4 mb-0'),
                Column('north', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', 'Submit')
        )


class SearchForm(forms.Form):
    geoid = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'GeoID'}))
    rate = forms.ChoiceField(choices=RATE)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'geoid',
            'rate',
            Submit('submit', 'Submit')
        )

datamanager/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.template import loader, RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse, reverse_lazy
from django.db import connection
from django.views import generic
from .models import Tidychampaign, Rate, Socio, CommentDB
from .forms import UserInfoForm, CommentForm, recommandationForm, SearchForm
from .pyScript import score
import pandas as pd

#   Straightforward function.
def index(request):
    template = loader.get_template('datamanager/index.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


#   This is a very important function which might be changed several time in the future.
#   This function handle nearly all request for the detail page for a data record.
#
#   It handles: 1) listing all attribute for that record in Tidychampaign database
#               2) display all the comments from current logged-in user towards this data record.
#               3) display the form for user to write a new comment or provide the UI for user to manage their
#                  comments
#   Feel free to add additional features if you want.
def detail(request, geoid):
    if request.method == "GET":
        all_comment = []
        user_comment = []
        avg_rate = 0
        username = request.user.username
        template = loader.get_template('datamanager/detail.html')
        place = get_object_or_404(Tidychampaign, pk=geoid)

        allCommentQuery = """\
                   SELECT *
                   FROM CommentDB
                   WHERE GEOID = %s;
                   """

        userCommentQuery = """\
                   SELECT *
                   FROM CommentDB
                   WHERE GEOID = %s AND Username = '%s';
                   """
        calRateQuery = """\
                   SELECT ROUND(AVG(Rate), 2)
                   FROM CommentDB
                   WHERE GEOID = %s;
                   """
        with connection.cursor() as cursor:
                cursor.execute(calRateQuery % (geoid))
                avg_rate = cursor.fetchone()
                cursor.execute(userCommentQuery % (geoid, username))
                user_comment = cursor.fetchall()
                cursor.execute(allCommentQuery % (geoid))
                all_comment = cursor.fetchall()

        form = CommentForm()


        context = {
            'record' : place,
            'form' : form,
            'all_comment' : all_comment,
            'user_comment' : user_comment,
            'avg_rate': avg_rate,
        }
        return HttpResponse(template.render(context, request))

    else:
        form = CommentForm(request.POST)
        emptyFrom = CommentForm()
        template = loader.get_template('datamanager/detail.html')
        place = get_object_or_404(Tidychampaign, pk=geoid)
        Username = request.user.username
        all_comment = []
        user_comment = []
        avg_rate = 0.0
        rate = 0

        if form.is_valid():
            username = request.user.username
            rate = form['rate'].value()
            comment = form['comment'].value()

            allCommentQuery = """\
                       SELECT *
                       FROM CommentDB
                       WHERE GEOID = %s;
                       """

            userCommentQuery = """\
                       SELECT *
                       FROM CommentDB
                       WHERE GEOID = %s AND Username = '%s';
                       """

            insertQuery = """\
                        INSERT INTO CommentDB(GEOID, Username, Rate, Comment)
                        VALUES (%s, '%s', %s, '%s');
                        """
            calRateQuery = """\
                       SELECT ROUND(AVG(Rate), 2)
                       FROM CommentDB
                       WHERE GEOID = %s;
                       """

            # insertRateQuery = """\
            #            INSERT INTO rate(Username, Race, Gender, Age, Dept, Block, Rate)
            #             VALUES ('%s', '%s', '%s', %s, '%s', '%s', %s);
            #            """
            insertRateQuery = """\
                       INSERT INTO rate(Username, Rate)
                        VALUES ('%s', %s);
                       """
            # nrace = None
            # ngender = None
            # nage = None
            # ndept = None
            # nblock = None

            with connection.cursor() as cursor:
                cursor.execute(insertQuery % (geoid, username, rate, comment))
                cursor.execute(userCommentQuery % (geoid, username))
                user_comment = cursor.fetchall()
                cursor.execute(allCommentQuery % (geoid))
                all_comment = cursor.fetchall()
                cursor.execute(calRateQuery % (geoid))
                avg_rate = cursor.fetchone()
                # cursor.execute(insertRateQuery % (username, nrace, ngender, nage, ndept, nblock, rate))
                cursor.execute(insertRateQuery % (username, rate))

        context = {
            'record' : place,
            'form' : form,
            'all_comment' : all_comment,
            'user_comment' : user_comment,
            'avg_rate': avg_rate,
        }
        return HttpResponse(template.render(context, request))


#   This function is used to handled the request when user want to delete one of their comment.
#   I think this function is working very well. Feel free to change it if you find any bugs.
def deleteComment(request, geoid, context):
    username = request.user.username

    deleteQuery = """\
                DELETE FROM CommentDB
                WHERE GEOID = %s AND Username = '%s' AND Comment = '%s';
                """
    with connection.cursor() as cursor:
        cursor.execute(deleteQuery % (geoid, username, context))

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


#   This function is for user provide their data (race, gender, location, etc.) to our database.
#   User provide their data via fill out a form. You can go to forms.py and take a look at UserInfoForm
#   function to have a better look.
#
#   The function here is just a first draft. Here are some potential improvements you can make:
#   1. The query for updating Tidychampaign database is very bad.
#           * It doesn't handle the case when user choose 'Prefer not to answer' option.
#           * Each user should only upload their data once. This query doesn't handle this case
#   2. Since we want each user can only update the query once, it would be nice if we can implement the
#      feature that after the user filled out the form once, it will display 'Thank you for your contribution!
#      You have filled out this form before!' (or stuff like this). We don't want a single user update the database
#      multiple times.
def newdata(request, username):
    if request.method == "GET":
        template = loader.get_template('datamanager/newdata.html')
        form = UserInfoForm()
        context = {
            'username' : username,
            'form' : form,
        }
    else:
        form = UserInfoForm(request.POST)
        if form.is_valid():
            username = request.user.username;
            geoid = form['geoid'].value()
            age = form['age'].value()
            race = form['race'].value()
            gender = form['gender'].value()
            dept = form['dept'].value()
            dictRaceGender = {
                "B" : "Black",
                "W" : "White",
                "A" : "Asian",
                "F" : "Female",
                "M" : "Male"
            }
            list = [race,gender];
            for item in list:
                if item != 'NA':

                    query = """\
                        UPDATE Tidychampaign
                        SET %s = %s + 1
                        WHERE GEOID = %s;
                        """
                    with connection.cursor() as cursor:
                         cursor.execute(query % (dictRaceGender[item], dictRaceGender[item], geoid))
            query = """\
                UPDATE Tidychampaign
                SET Population = Population + 1
                WHERE GEOID = %s;
                """
            with connection.cursor() as cursor:
                 cursor.execute(query %geoid)
            query = """\
                SELECT Block FROM Tidychampaign WHERE GEOID = %s
                """

            with connection.cursor() as cursor:
                 cursor.execute(query %geoid)
                 block = cursor.fetchone()[0]

            insertInfoQuery = """\
                INSERT INTO UserInfo(Username, Race, Gender, Age, Dept, Block)
                VALUES ('%s', '%s', '%s', %s, '%s','%s');
                """
            with connection.cursor() as cursor:
                 cursor.execute(insertInfoQuery %(username,race,gender,age,dept,block))

        template = loader.get_template('datamanager/thanks.html')
        context = {
            'username' : username,
        }
    return HttpResponse(template.render(context, request))


#   This function is for listing all data record in our database. As you can see, I use the 'paginator' API for
#   this feature. If you are not familiar with this API, you can google it and see the documentation for reference.
def datalist(request):
    username = request.user.username
    records = Tidychampaign.objects.order_by("geoid")
    print(type(records))
    paginator = Paginator(records, 10)
    page = request.GET.get('page')
    try:
        show_records = paginator.page(page)
    except PageNotAnInteger:
        show_records = paginator.page(1)
    except EmptyPage:

datamanager/templates/datamanager/datalist.html
{% extends 'datamanager/base.html' %}

{% load bootstrap_toolkit %}
{% load bootstrap_pagination %}
{% block title %}Data List{% endblock %}

{% block link %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock link %} 

{% block login %}
    <form action="{% url 'datamanager:index' %}" method="POST">
        {% csrf_token %}
        <button type="submit">Back to main page</button>
    </form>    
{% endblock %}

{% block content %}

      <table class="table table-striped table-hover">
        <tr>
            <td><strong>GeoID</strong></td>
            <td><strong>Block</strong></td>
            <td><strong>Population</strong></td>
        </tr>
        {% for record in records %}
            <tr>
                <td><a href="{% url 'datamanager:detail' record.geoid %}">{{ record.geoid }}</a></td>
                <td><p>{{ record.block }}</p></td>
                <td><p>{{ record.population }}</p></td>
            </tr>
        {% endfor %}
    </table>
 
    <div class="pagination">
        <div class="pagination-row text-right ">
            {% bootstrap_paginate records range=8 %}
        </div>
    </div>
    
{% endblock %}

datamanager/templates/datamanager/detail.html
{% extends 'datamanager/base.html' %}

{% load bootstrap_toolkit %}
{% load bootstrap_pagination %}
{% load crispy_forms_tags %}

{% block title %}Record detail{% endblock %}

{% block link %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock link %}

{% block login %}
    <form action="{% url 'datamanager:datalist' %}" method="GET">
        {% csrf_token %}
        <button type="submit">Back to data list</button>
    </form>
{% endblock %}

{% block content %}

    <table class="table table-striped table-hover">
        <tr>
            <td><strong>GeoID</strong></td>
            <td><strong>Block</strong></td>
            <td><strong>Population</strong></td>
            <td><strong>Geography</strong></td>
            <td><strong>White</strong></td>
            <td><strong>Black</strong></td>
            <td><strong>Asian</strong></td>
            <td><strong>OtherRace</strong></td>
            <td><strong>Male</strong></td>
            <td><strong>Female</strong></td>
            <td><strong>Young</strong></td>
            <td><strong>Middle</strong></td>
            <td><strong>Old</strong></td>
        </tr>
        <tr>
            <td><p>{{ record.geoid }}</p></td>
            <td><p>{{ record.block }}</p></td>
            <td><p>{{ record.population }}</p></td>
            <td><p>{{ record.geography }}</p></td>
            <td><p>{{ record.white }}</p></td>
            <td><p>{{ record.black }}</p></td>
            <td><p>{{ record.asian }}</p></td>
            <td><p>{{ record.otherrace }}</p></td>
            <td><p>{{ record.male }}</p></td>
            <td><p>{{ record.female }}</p></td>
            <td><p>{{ record.young }}</p></td>
            <td><p>{{ record.middle }}</p></td>
            <td><p>{{ record.old }}</p></td>
        </tr>
    </table>

    <table class="table table-striped table-hover">
        <tr>
            <td><strong>Users' Rate</strong></td>
        </tr>
        <tr>
            <td><p>{{ avg_rate.0 }}</p></td>
        </tr>
    </table>

    <br>

    {% if user_comment %}
        <table class="table table-striped table-hover">
            <caption>All comments</caption>
            <tr>
                <td><strong>Username</strong></td>
                <td><strong>Rate</strong></td>
                <td><strong>Comment</strong></td>
            </tr>
            {% for comment_entry in all_comment %}
            <tr>
                <td><p>{{ comment_entry.0 }}</p></td>
                <td><p>{{ comment_entry.2 }}</p></td>
                <td><p>{{ comment_entry.3 }}</p></td>
            </tr>
            {% endfor %}
        </table>
    {% endif %}

    {% if all_comment %}
        <table class="table table-striped table-hover">
            <caption>Your comments</caption>
            <tr>
                <td><strong>Username</strong></td>
                <td><strong>Your Rate</strong></td>
                <td><strong>Your Comment</strong></td>
                <td><strong>Action</strong></td>
            </tr>
            {% for comment_entry in user_comment %}
            <tr>
                <td><p>{{ comment_entry.0 }}</p></td>
                <td><p>{{ comment_entry.2 }}</p></td>
                <td><p>{{ comment_entry.3 }}</p></td>
                <td>
                    <form action="{% url 'datamanager:deleteComment' comment_entry.1 comment_entry.3 %}" method="POST">
                        {% csrf_token %}
                        <div class="buttonWrapper">
                            <button type="submit">Delete</button>
                        </div>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% endif %}
    <br>

    <form method="POST">
        {% csrf_token %}
        {% crispy form %}
    </form>
{% endblock %}

datamanager/templates/datamanager/index.html
{% extends 'datamanager/base.html' %}

{% block title %}Iteractive Community Envrionment Mapping{% endblock %}
{% block login %}
    {% if user.is_authenticated %}
        <div class="newdataContainer">
            <h2>Hi {{ user.username }}!</h2>
            <form action="{% url 'datamanager:logout' %}" method="POST">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
            <form action="{% url 'datamanager:newdata' user.username %}" method="GET">
                {% csrf_token %}
                <button type="submit">Provide data</button>
            </form>
            <form action="{% url 'datamanager:datalist' %}" method="GET">
                {% csrf_token %}
                <button type="submit">Data List</button>
            </form>
            <form action="{% url 'datamanager:search' %}" method="GET">
                {% csrf_token %}
                <button type="submit">Search</button>
            </form>     
            <form action="{% url 'datamanager:recommandation' %}" method="GET">
                {% csrf_token %}
                <button type="submit">Recommandation</button>
            </form>    
        </div>
    {% else %}
        <form action="{% url 'datamanager:login' %}" method="POST">
            {% csrf_token %}
            <button type="submit">Login</button>
        </form>
    {% endif %}
{% endblock %}

{% block content %}
    <div class='interactiveMap'>
        <h2>Interactive Map</h2>
        <img src="../../static/datamanager/champaign.jpg">
    </div>
{% endblock content %}

datamanager/templates/datamanager/newdata.html
{% extends 'datamanager/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Iteractive Community Envrionment Mapping{% endblock %}

{% block link %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock link %}

{% block login %}
    {% if username %}
        <h2>Hi {{ user.username }}!</h2>
        <form action="{% url 'datamanager:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit">Logout</button>
        </form>
    {% else %}
        <form action="{% url 'datamanager:login' %}" method="POST">
            {% csrf_token %}
            <button type="submit">Login</button>
        </form>
    {% endif %}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% crispy form %}
    </form>
{% endblock content %}

datamanager/templates/datamanager/recommandation.html
{% extends 'datamanager/base.html' %}

{% load bootstrap_toolkit %}
{% load bootstrap_pagination %}
{% load crispy_forms_tags %}

{% block title %}Recommandation{% endblock %}

{% block link %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock link %}

{% block login %}
    <form action="{% url 'datamanager:index' %}" method="POST">
        {% csrf_token %}
        <button type="submit">Back to main page</button>
    </form>
{% endblock %}

{% block content %}
    <h2 class='engineDescription'>The search engine is based on a self-updated machine learning algorithm with statistical adjustment of users' preferences.</h2>
    {% if form %}
        <caption>Default values are set to 'prefer'. 
        </caption>
        <form method="POST">
            {% csrf_token %}
            {% crispy form %}
        </form>
    {% else %}
        {% if record_list %}
            <table class="table table-striped table-hover">
                <tr>
                    <td><strong>GeoID</strong></td>
                    <td><strong>Score</strong></td>
                    <td><strong>South</strong></td>
                    <td><strong>North</strong></td>
                    <td><strong>Main</strong></td>
                    <td><strong>Longitude</strong></td>
                    <td><strong>Latitude</strong></td>
                    <td><strong>Rank</strong></td>
                </tr>
                {% for record in record_list %}
                    <tr>
                        <td><a href="{% url 'datamanager:detail' record.0 %}">{{ record.0 }}</a></td>
                        <td><p>{{ record.1 }}</p></td>
                        <td><p>{{ record.2 }}</p></td>
                        <td><p>{{ record.3 }}</p></td>
                        <td><p>{{ record.4 }}</p></td>
                        <td><p>{{ record.5 }}</p></td>
                        <td><p>{{ record.6 }}</p></td>
                        <td><p>{{ forloop.counter }}</p></td>
                    </tr>
                {% endfor %}
            </table>
            <div>
                <a href="{% url 'datamanager:google' %}"  class="urlsLink">Google Map</a>
                <a href="{% url 'datamanager:heat' %} " class="urlsLink">Heat Map</a>
            </div>
        {% else %}
            <h2 class="Recommandation">
                Sorry! No matching records!!!
            </h2>
        {% endif %}
    {% endif %}

    
{% endblock %}

datamanager/templates/datamanager/searchResult.html
{% extends 'datamanager/base.html' %}

{% load bootstrap_toolkit %}
{% load bootstrap_pagination %}
{% block title %}Data List{% endblock %}

{% block link %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock link %} 

{% block login %}
    <form action="{% url 'datamanager:index' %}" method="POST">
        {% csrf_token %}
        <button type="submit">Back to main page</button>
    </form>    
{% endblock %}

{% block content %}



      <table class="table table-striped table-hover">
        <tr>
            <td><strong>GeoID</strong></td>
        </tr>
        {% for record in records %}
            <tr>
                <td><a href="{% url 'datamanager:detail' record %}">{{ record }}</a></td>
            </tr>
        {% endfor %}
    </table>
    
{% endblock %}